In [1]:
import numpy as np

In [2]:
list = [1,2,324,53,46,45,75,67,6,8,65]

In [4]:
array = np.array(list)
print(array)
print(type(array))

[  1   2 324  53  46  45  75  67   6   8  65]
<class 'numpy.ndarray'>


### Creating a range using Numpy

In [5]:
range = np.arange(0, 20, 2, dtype=int)

In [6]:
print(range)

[ 0  2  4  6  8 10 12 14 16 18]


### matrix of zeros

In [8]:
zeros = np.zeros((3,5)) #matrix of (3,5)
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Linearly spaced Numbers

In [11]:
linear = np.linspace(0, 20, 40)  # linearly spaced number with the differnce of 0.5
print(linear)

[ 0.          0.51282051  1.02564103  1.53846154  2.05128205  2.56410256
  3.07692308  3.58974359  4.1025641   4.61538462  5.12820513  5.64102564
  6.15384615  6.66666667  7.17948718  7.69230769  8.20512821  8.71794872
  9.23076923  9.74358974 10.25641026 10.76923077 11.28205128 11.79487179
 12.30769231 12.82051282 13.33333333 13.84615385 14.35897436 14.87179487
 15.38461538 15.8974359  16.41025641 16.92307692 17.43589744 17.94871795
 18.46153846 18.97435897 19.48717949 20.        ]


### Generating the random number

In [12]:
random_numbers = np.random.randint(0, 100, 20, dtype=int)
print(random_numbers)

[52 72 25 10 96 40 96 22 63  0 75 88  3  3 69 68 11 83 59  9]


### Generating the random numbers with dimensions

In [13]:
random_number = np.random.randint(low=0, high = 100, size= (3,3) )
print(random_number)

[[45 85 25]
 [28 92 33]
 [98 62 73]]


### Arthmetic operations 

In [14]:
random_number.max()

98

In [15]:
random_number.min()

25

In [16]:
random_number.mean()

60.111111111111114

In [17]:
random_number.sum()

541

In [18]:
random_number.diagonal()

array([45, 92, 73])

In [19]:
random_number.flatten() #into an array

array([45, 85, 25, 28, 92, 33, 98, 62, 73])

In [20]:
random_number.reshape(3,3) # reshape into any dimension. It should fill all the elements

array([[45, 85, 25],
       [28, 92, 33],
       [98, 62, 73]])

### Matrix operation

In [25]:
matrix = np.arange(start = 0 ,stop = 100 , step =4).reshape(5,5)
print(matrix)

[[ 0  4  8 12 16]
 [20 24 28 32 36]
 [40 44 48 52 56]
 [60 64 68 72 76]
 [80 84 88 92 96]]


In [ ]:
N