# SciKit-Learn for preprocessing the data

### Scaling and Splitting the data

In [2]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100, (10,2))

In [4]:
print(data)

[[53 36]
 [79 84]
 [82 13]
 [46 10]
 [55 86]
 [ 7 54]
 [33 84]
 [84 70]
 [13 66]
 [61 44]]


In [5]:
scaler_model = MinMaxScaler()

In [6]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [7]:
scaler_model.fit(data)

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [9]:
####### Here minimum value will become 0. and max value will become 1.

In [10]:
scaler_model.fit_transform(data)

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.5974026 , 0.34210526],
       [0.93506494, 0.97368421],
       [0.97402597, 0.03947368],
       [0.50649351, 0.        ],
       [0.62337662, 1.        ],
       [0.        , 0.57894737],
       [0.33766234, 0.97368421],
       [1.        , 0.78947368],
       [0.07792208, 0.73684211],
       [0.7012987 , 0.44736842]])

### Train test split using pandas

In [11]:
import pandas as pd

/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [12]:
my_data = np.random.randint(0,100, (50,4))

In [13]:
print(my_data)

[[30 99 56 81]
 [37 28 75 16]
 [65 19 68 94]
 [45 15 31 95]
 [22 94 78 28]
 [73 24 86  3]
 [78 85 46 94]
 [93 81 10 89]
 [77 25 92 98]
 [84 19  9 82]
 [28 73 31 67]
 [54 26 86 86]
 [71 46  2  3]
 [65 28 38 33]
 [ 9 27  6 56]
 [65 21 53 94]
 [97 48 67 36]
 [92 15 65 23]
 [83 48 91 73]
 [81 73 43 91]
 [80 42 10 25]
 [28 52  4 78]
 [44 97 56 21]
 [73 89 17 28]
 [59 45 58 99]
 [59 73 32 88]
 [43 34 46 90]
 [17 36 46 25]
 [ 6 94 21 20]
 [68 85 66 80]
 [47 22 35 38]
 [58 60 18 62]
 [54 88 89 79]
 [28  2 51 27]
 [92 41 44 92]
 [84  8 62  7]
 [33 14 73 65]
 [65 72 33 44]
 [97 20 74 90]
 [21  0 61 35]
 [16 47 97  4]
 [89 89  7 52]
 [15 36 55 69]
 [46 81 86 60]
 [45 77 82  7]
 [36  1 91 94]
 [24 30 86 30]
 [34 58 51 80]
 [21 34 27 44]
 [73 54 28 60]]


#### Labelling the Columns

In [19]:
df = pd.DataFrame(data=my_data, columns=['f1','f2', 'f3','label'])

In [20]:
print(df)

    f1  f2  f3  label
0   30  99  56     81
1   37  28  75     16
2   65  19  68     94
3   45  15  31     95
4   22  94  78     28
5   73  24  86      3
6   78  85  46     94
7   93  81  10     89
8   77  25  92     98
9   84  19   9     82
10  28  73  31     67
11  54  26  86     86
12  71  46   2      3
13  65  28  38     33
14   9  27   6     56
15  65  21  53     94
16  97  48  67     36
17  92  15  65     23
18  83  48  91     73
19  81  73  43     91
20  80  42  10     25
21  28  52   4     78
22  44  97  56     21
23  73  89  17     28
24  59  45  58     99
25  59  73  32     88
26  43  34  46     90
27  17  36  46     25
28   6  94  21     20
29  68  85  66     80
30  47  22  35     38
31  58  60  18     62
32  54  88  89     79
33  28   2  51     27
34  92  41  44     92
35  84   8  62      7
36  33  14  73     65
37  65  72  33     44
38  97  20  74     90
39  21   0  61     35
40  16  47  97      4
41  89  89   7     52
42  15  36  55     69
43  46  81  86     60
44  45  77

In [21]:
X = df[['f1','f2','f3']]

In [24]:
y= df['label']

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size=0.2)