In [2]:
import tensorflow as tf
import numpy as np

/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [3]:
np.random.seed(101)
tf.set_random_seed(101)

In [4]:
# Let's create some random variables
rand_a = np.random.uniform(0,100,(5,5))
rand_b = np.random.uniform(0,100,(5,1))

In [5]:
# Let's create some PlaceHolders
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)

In [6]:
# Let's create some operations
add_op = a+b
mul_op = a*b

In [7]:
# Let's create some session to execute these operations into the session

In [8]:
with tf.Session() as sess:
   add_results = sess.run(add_op, feed_dict={a:rand_a, b:rand_b})
   print(add_results) 

[[ 151.07165527  156.49855042  102.27921295  116.58396149  167.95948792]
 [ 135.45622253   82.76316071  141.42784119  124.22093201   71.06043243]
 [ 113.30171204   93.09214783   76.06819153  136.43911743  154.42727661]
 [  96.7172699    81.83804321  133.83674622  146.38117981  101.10578918]
 [ 122.72680664  105.98292542   59.04463196   67.98310089   72.89292145]]


In [9]:
with tf.Session() as sess:
    result = sess.run(mul_op, feed_dict={a:rand_a, b:rand_b})
    print (result)

[[ 5134.64404297  5674.25         283.12432861  1705.47070312
   6813.83154297]
 [ 4341.8125      1598.26696777  4652.73388672  3756.8293457    988.9463501 ]
 [ 3207.8112793   2038.10290527  1052.77416992  4546.98046875
   5588.11572266]
 [ 1707.37902832   614.02526855  4434.98876953  5356.77734375
   2029.85546875]
 [ 3714.09838867  2806.64379883   262.76763916   747.19854736
   1013.29199219]]
