In [2]:
import tensorflow as tf

In [3]:
sess = tf.InteractiveSession()

In [4]:
fill_matrix = tf.fill((4,4),10)

In [5]:
myrandomn=tf.random_normal((4,4), mean=0, stddev=1.0)

# Create a list to call above tensor's

In [6]:
my_ops = [fill_matrix,myrandomn]

In [8]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 1.38149679 -0.33418757  1.05823541  0.01035366]
 [-0.06243692  0.36276847  2.0874126   3.101228  ]
 [-0.53601032  1.28612649  0.76243854 -0.15027207]
 [ 0.45438287  0.93144214 -0.65646541 -1.47373104]]




# Eval function

In [10]:
#eval function replaces the session run for all the sessions.
for op in my_ops:
    print(op.eval())
    print('\n')

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[-0.15485981  0.82729352  0.74943238  1.85608339]
 [ 0.54685599  0.9840219   0.08238363 -0.83969182]
 [-0.23317616 -0.8738752  -0.74591076 -1.79611671]
 [ 0.04544037  0.16706716  0.87926048  1.4308604 ]]




# Matrix basics in TF

In [12]:
a = tf.constant([[1,2], [3,4]])

In [13]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [14]:
b = tf.constant([[1],[100]])

In [15]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [16]:
# Multiplying the matrices
results = tf.matmul(a,b)

In [17]:
sess.run(results)

array([[201],
       [403]], dtype=int32)

In [18]:
#same with eval()
results.eval()

array([[201],
       [403]], dtype=int32)